export const articles = [
  {
    id: '1',
    date: '2018-05-03T15:03:23.000Z',
    title: 'Classes in JavaScript - Explained',
    language: 'eng',
    link: 'http://blog.brew.com.hk/classes-in-javascript-explained/',
    text: 'This article is an extended adaptation from Understanding Prototypes in JavaScript. This article is very in-depth, and may require a second reading to really grok it. JavaScript is unique because it can be used as an object-orientated programming (OOP) language, but it also has a lot of functional aspects built into it. Furthermore, unlike classic OOP languages such as Java, its inheritance model is not class-based, but rather prototype-based. So what\'s the difference?',
    tags: ['javaScript'],
  },
  {
    id: '2',
    date: '2018-05-03T15:03:23.000Z',
    title: 'Операторы ?., ?? и |>: будущие возможности JavaScript, которые вам понравятся',
    language: 'ru',
    link: 'https://habr.com/company/ruvds/blog/353446/',
    text: 'Джастин Фуллер, автор материала, перевод которого мы сегодня публикуем, предлагает рассмотреть три новых возможности, появление которых ожидается в JavaScript в обозримом будущем. </br> Сначала он расскажет о процессе развития JS, а после этого представит обзор этих возможностей и покажет примеры их использования. Речь пойдёт об операторах ?., ?? и |>.',
    tags: ['javaScript'],
  },
  {
    id: '3',
    date: '2018-04-12T15:03:23.000Z',
    title: 'Scroll to the future',
    language: 'eng',
    link: 'https://evilmartians.com/chronicles/scroll-to-the-future-modern-javascript-css-scrolling-implementations',
    text: 'Прокрутка в будущее! Вообще всё, что вы хотели знать про реализацию прокрутки, но боялись спросить. Анна Селезнёва и Андрей Барнов в блоге Злых марсиан',
    tags: ['javaScript'],
  },
  {
    id: '4',
    date: '2018-04-14T15:03:23.000Z',
    title: 'Веб-воркеры в JavaScript: безопасный параллелизм',
    language: 'ru',
    link: 'https://habr.com/company/ruvds/blog/352828/',
    text: 'В материале рассмотрены особенности использования веб-воркеров для решения задач, которые слишком тяжелы для главного потока. В частности, речь здесь пойдёт о том, как организовать обмен данными между главным потоком и потоком веб-воркера. Здесь же будет рассмотрена пара примеров, иллюстрирующих различные сценарии использования веб-воркеров.',
    tags: ['javaScript'],
  },
  {
    id: '5',
    date: '2018-05-04T15:03:23.000Z',
    title: 'Классы и фабричные функции в JavaScript. Что выбрать?',
    language: 'ru',
    link: 'https://habr.com/company/ruvds/blog/352198/',
    text: 'В JavaScript существуют разные способы создания объектов. В частности, речь идёт о конструкциях, использующих ключевое слово class и о так называемых фабричных функциях (Factory Function). Автор материала, перевод которого мы публикуем сегодня, исследует и сравнивает эти две концепции в поисках ответа на вопрос о плюсах и минусах каждой из них.',
    tags: ['javaScript'],
  },
  {
    id: '6',
    date: '2018-05-03T15:03:23.000Z',
    title: 'Элегантные паттерны современного JavaScript: RORO',
    language: 'ru',
    link: 'https://habr.com/company/ruvds/blog/350536/',
    text: 'В этой статье Билл Соро хочет рассказать о замечательном маленьком паттерне, которым он уже какое-то время с удовольствием пользуется. Он надеется, что этот шаблон проектирования пригодится и другим программистам. Билл говорит, что не считает себя первооткрывателем этого паттерна, скорее, речь идёт о том, что он увидел нечто подобное в чьём-то коде, а потом адаптировал это под свои нужды.',
    tags: ['javaScript'],
  },
  {
    id: '7',
    date: '2018-05-03T15:03:23.000Z',
    title: 'Элегантные паттерны современного JavaScript: Ice Factory',
    language: 'ru',
    link: 'https://habr.com/company/ruvds/blog/351800/',
    text: 'Предлагаем вашему вниманию перевод очередного материала Билла Соро, который посвящён шаблонам проектирования в JavaScript. В прошлый раз мы рассказывали о паттерне RORO, а сегодня нашей темой будет шаблон Ice Factory. Если в двух словах, то этот шаблон представляет собой функцию, которая возвращает «замороженный» объект. Это — очень важный и мощный паттерн, и разговор о нём мы начнём с описания одной из проблем JS, на решение которой он направлен.',
    tags: ['javaScript'],
  },
  {
    id: '8',
    date: '2018-03-07T15:03:23.000Z',
    title: 'CSS Paint API — New and Glossy, but What Is It For?',
    language: 'eng',
    link: 'https://www.codementor.io/brettjephson/css-paint-api-new-and-glossy-but-what-is-it-for-gpd44fl03',
    text: 'Обзор нового The CSS Paint API, доступного в Chrome 65',
    tags: ['javaScript', 'css'],
  },
  {
    id: '9',
    date: '2018-03-13T15:03:23.000Z',
    title: 'Designing Button States',
    language: 'eng',
    link: 'https://cloudfour.com/thinks/designing-button-states/',
    text: 'Дизайн состояний кнопки. Тайлер Стика с введением в основные принципы создания удобных, доступных и понятных кнопок',
    tags: ['UIUX', 'design'],
  },
  {
    id: '10',
    date: '2018-02-20T15:03:23.000Z',
    title: '7 Practical Tips for Cheating at Design',
    language: 'eng',
    link: 'https://medium.com/refactoring-ui/7-practical-tips-for-cheating-at-design-40c736799886',
    text: '7 практических советов о том, как улучшить ваш проект, даже если у вас нет опыта в разработке дизайна. На мой взгляд очень интересно и полезно для тех кто интересуется дизайном.',
    tags: ['design'],
  },
  {
    id: '11',
    date: '2018-02-20T15:03:23.000Z',
    title: 'Что не так с Emoji. Алексей Авдеев',
    language: 'ru',
    link: 'https://youtu.be/DUwZpLBSuiI',
    text: 'Почему эмоджи выглядят по-разному в разных браузерах? Что делать, если дизайнеры говорят, что все смайлики должны выглядеть, как на Айфоне? Решаем проблему, попутно разбираясь в спецификациях Emoji и Unicode.',
    tags: ['design', 'youTube'],
  },
  {
    id: '12',
    date: '2016-08-25T15:03:23.000Z',
    title: 'Введение в каррирование в JavaScript',
    language: 'ru',
    link: 'http://prgssr.ru/development/vvedenie-v-karrirovanie-v-javascript.html',
    text: 'Каррирование или частичное применение это одна из техник функционального программирования, которая может показаться странной людям, знакомым с более традиционными способами написания JavaScript. Но при правильном применении каррирование действительно способно сделать ваш JavaScript более читаемым.',
    tags: ['javaScript'],
  },
  {
    id: '13',
    date: '2018-05-12T15:03:23.000Z',
    title: 'JavaScript Symbols, Iterators, Generators, Async/Await, and Async Iterators — All Explained Simply',
    language: 'eng',
    link: 'https://medium.freecodecamp.org/some-of-javascripts-most-useful-features-can-be-tricky-let-me-explain-them-4003d7bbed32?gi=3d4c3b0091e6',
    text: 'Хорошее объяснение применения Символов, Итераторов, Генераторов, async/await и асинхронных итераторов.',
    tags: ['javaScript'],
  },
  {
    id: '14',
    date: '2018-05-12T15:03:23.000Z',
    title: 'Асинхронность в JavaScript. Таймеры, промисы, async/await',
    language: 'ru',
    link: 'https://youtu.be/Ih6Q7ka2eSQ',
    text: 'Один из лучших вебинаров по объяснению асинхронности в JavaScript. ',
    tags: ['javaScript', 'youTube'],
  },
  {
    id: '15',
    date: '2018-05-14T15:03:23.000Z',
    title: 'Движение по траектории в CSS помимо «большой тройки» свойств',
    language: 'ru',
    link: 'http://css-live.ru/articles/dvizhenie-po-traektorii-v-css-pomimo-bolshoj-trojki-svojstv',
    text: 'Описание будущих возможностей анимации CSS (CSS Motion Path). Поддержка пока только в Chrome, но выглядит достаточно многообещающе.',
    tags: ['css'],
  },
  {
    id: '16',
    date: '2018-06-28T15:03:23.000Z',
    title: 'Spacings and CSS Custom properties',
    language: 'eng',
    link: 'https://voices.basedesign.com/spacings-and-css-custom-properties-bdae00eaf3f1',
    text: 'Система отступов на кастомных CSS-свойствах. Луис Хобрегтс переключает значения свойств с помощью медиавыражений для гармоничной адапатции с фолбэком на ремы для старых браузеров',
    tags: ['css', 'design'],
  },
  {
    id: '17',
    date: '2018-07-04T15:03:23.000Z',
    title: 'Как и зачем тестировать верстку',
    language: 'ru',
    link: 'https://medium.com/p/84a378bf7bb4',
    text: 'Регрессионное тестирование верстки на BackstopJS',
    tags: ['javaScript'],
  },
  {
    id: '18',
    date: '2018-07-15T15:03:23.000Z',
    title: 'How to GraphQL - The Fullstack Tutorial for GraphQL',
    language: 'eng',
    link: 'https://www.howtographql.com/',
    text: 'Fullstack GraphQL Tutorial, от нуля до production, охватывая все основы и передовые концепции.',
    tags: ['javaScript', 'graphQL'],
  },
  {
    id: '19',
    date: '2017-02-15T15:03:23.000Z',
    title: 'Немного о современной русской типографике',
    language: 'ru',
    link: 'http://sudzhuk.com/blog/2017/02/15/4913/',
    text: 'Хороший экскурс в типографику от Артемия Коберника. Разбор основных правил и примеров правильного использования.',
    tags: ['typography', 'design'],
  },
  {
    id: '20',
    date: '2017-07-10T15:03:23.000Z',
    title: 'Уровень развития CSS: пристальный взгляд на CSS архитектуры',
    language: 'ru',
    link: 'http://jem-space.ru/urovien-razvitiia-v-css-pristalnyi-vzghliad-na-css-arkhitiektury/',
    text: 'Мы все знаем, что организация, порядок и модульность - это ключ к успеху при работе с CSS, и поэтому CSS архитектуры становятся все более популярными. В данной статье описаны основные существующие CSS архитектуры.',
    tags: ['css'],
  },
  {
    id: '21',
    date: '2018-08-15T15:03:23.000Z',
    title: '5 приемов работы с CSS, о которых вам следует знать',
    language: 'ru',
    link: 'https://habr.com/post/420307/',
    text: 'Наблюдая за потоком вопросов по CSS на Тостере уже давно заметил, что многие из них повторяются много-много раз. Да, есть совсем глупые вопросы, на которые так и тянет ответить RTFM! Но есть и более занятные. Они связаны с не совсем стандартной версткой. Не такой, чтобы глаза на лоб лезли, но и заметно выходящей за рамки условного бутстрапа и традиционных туториалов для новичков. Похожие вопросы довольно сложно загуглить — обычно вся суть в картинке, но и отвечать каждый раз надоедает. В этой статье мы постараемся посмотреть некоторые приемы, охватывающие довольно широкий круг подобных вопросов. Информация в первую очередь адресуется начинающим верстальщикам, но возможно и опытным будет, чем вдохновиться.',
    tags: ['css'],
  },
  {
    id: '22',
    date: '2018-08-12T15:03:23.000Z',
    title: 'Pure CSS Moustached Nanny',
    language: 'eng',
    link: 'https://codepen.io/miocene/pen/mjLPVp',
    text: 'Отличный пример того что с помощью CSS можно делать просто удивительные вещи, если очень захотеть',
    tags: ['css', 'design'],
  },
  {
    id: '23',
    date: '2018-08-10T15:03:23.000Z',
    title: 'Git happens! 6 типичных ошибок Git и как их исправить',
    language: 'ru',
    link: 'https://habr.com/company/flant/blog/419733/',
    text: 'Весьма полезная заметка с инструкциями, которые помогают сохранить время и нервы в случае различных проблем, случающихся по мере работы с Git. Вряд ли они будут новы для опытных пользователей, но обязательно найдутся и те, кому они пригодятся.',
    tags: ['git'],
  },
  {
    id: '24',
    date: '2018-04-19T15:03:23.000Z',
    title: 'Что нужно и чего не нужно делать во время Code Review',
    language: 'ru',
    link: 'https://apptractor.ru/info/articles/chto-nuzhno-i-chego-ne-nuzhno-delat-vo-vremya-code-review.html',
    text: 'Не плохая статья про культуру проведения code review. Советы и примеры достаточно очевидные, однако стоит почитать даже ради того чтобы понять на сколько правильно сам даешь обратную связь людям.',
    tags: ['softSkills'],
  },
  {
    id: '25',
    date: '2018-08-23T15:03:23.000Z',
    title: 'RxJS по косточкам',
    language: 'ru',
    link: 'https://youtu.be/3rEDHnqn-Cw',
    text: 'Доклад Андрея Алексеева на MoscowJS 42 очень хорош для начала знакомства с RxJS. Андрей рассказывает про паттерны лежащие в основе RxJS, а так же описывает основные принципы работы и приводит практические примеры использования.',
    tags: ['javaScript', 'youTube'],
  },
  {
    id: '26',
    date: '2018-08-28T15:03:23.000Z',
    title: 'Шесть наиболее полезных докладов с Frontend Conf 2018',
    language: 'ru',
    link: 'https://habr.com/company/oleg-bunin/blog/420965/',
    text: 'В подборке нашлось место рассказу про то, как настраивать PWA-приложения и делать их более нативными. Отдельно затронуты вопросы транспиляции, где на примере API Яндекс.Карт показано, как можно писать на ES2015, получая на выходе ES3, и обеспечить поддержку IDE и линтеров. Еще одна история — про популярные форматы хранения изображений, их сжатие и варианты загрузки на мобильные устройства. Не менее хардкорный доклад про то, как перенести нагрузку, связанную с расчетом анимации, с CPU на видеокарту. Плюс два отдельных доклада про секреты и лайфхаки CSS.',
    tags: ['javaScript', 'css'],
  },
  {
    id: '27',
    date: '2018-07-30T15:03:23.000Z',
    title: 'Новые (и старые) единицы измерения в CSS, о которых вы никогда не слышали',
    language: 'ru',
    link: 'https://ru.hexlet.io/blog/posts/new-and-old-css-units',
    text: 'В статье рассказывается про новые единицы CSS, которые будут детально описаны в готовящемся CSS Value и Units Module Level 4.',
    tags: ['css'],
  },
  {
    id: '28',
    date: '2018-08-22T15:03:23.000Z',
    title: 'Введение в программирование шейдеров для верстальщиков',
    language: 'ru',
    link: 'https://habr.com/post/420847/',
    text: 'Хорошая статья для того чтобы начать знакомство с шейдерами. В статье приведена реализация интересных эффектов созданных с помощью шейдеров, можно покопаться в коде и для более глубокого понимания статьи.',
    tags: ['javaScript'],
  },
  {
    id: '29',
    date: '2018-07-10T15:03:23.000Z',
    title: 'Building the Google Photos Web UI',
    language: 'eng',
    link: 'https://medium.com/google-design/google-photos-45b714dfbed1',
    text: 'Интересная статья о том как строился UI Google Photos.',
    tags: ['javaScript', 'UIUX', 'design'],
  },
  {
    id: '30',
    date: '2018-09-05T15:03:23.000Z',
    title: 'Inside look at modern web browser (part 1)',
    language: 'eng',
    link: 'https://developers.google.com/web/updates/2018/09/inside-browser-part1',
    text: 'Марико Косака рассказывает про CPU, GPU и преимущества многопроцессорной архитектуры в картинках',
    tags: ['webTheory'],
  },
  {
    id: '31',
    date: '2018-09-08T15:03:23.000Z',
    title: 'Inside look at modern web browser (part 2)',
    language: 'eng',
    link: 'https://developers.google.com/web/updates/2018/09/inside-browser-part1',
    text: 'Марико Косака рассказывает, что происходит во время навигации по страницам, в картинках',
    tags: ['webTheory'],
  },
  {
    id: '32',
    date: '2018-08-30T15:03:23.000Z',
    title: 'Применяем мозаику Вороного, пикселизацию и геометрические маски в шейдерах для украшения сайта',
    language: 'ru',
    link: 'https://habr.com/post/421821/',
    text: 'Данная статья является логическим продолжением введения в программирование шейдеров для верстальщиков (ссылка на статью есть на сайте). В данной статье разбирается еще пару текстур, применяется на практике разбиение Вороного для создания мозаики из них, говорится о создании различных масок в шейдерах, о пикселизации, а также затрагиваются некоторые проблемы древнего синтаксиса GLSL, который до сих пор существует в браузерах.',
    tags: ['javaScript'],
  },
  {
    id: '33',
    date: '2018-09-06T15:03:23.000Z',
    title: '10 вещей, которые вы в конечном итоге узнаете о JavaScript-проектах.',
    language: 'ru',
    link: 'https://medium.com/devschacht/the-cat-with-a-dragon-tattoo-10-things-you-will-eventually-learn-about-javascript-projects-f3848becd460',
    text: 'JavaScript — это приключение, или 10 вещей, которые вы в конечном итоге узнаете о JavaScript-проектах.',
    tags: ['javaScript'],
  },
  {
    id: '34',
    date: '2018-07-31T15:03:23.000Z',
    title: 'How to use Media Queries in JavaScript with matchMedia',
    language: 'eng',
    link: 'https://www.sitepoint.com/javascript-media-queries/',
    text: 'Небольшая заметка про использование функции window.matchMedia, которая позволяет работать с медиа выражениями в JS.',
    tags: ['javaScript'],
  },
  {
    id: '35',
    date: '2018-09-06T15:03:23.000Z',
    title: 'Игры с пользовательским восприятием и скорость работы веб-сайтов и приложений',
    language: 'ru',
    link: 'https://habr.com/company/alconost/blog/422437/',
    text: 'Статья о подходах в дизайне, которые помогут создать впечатление, что сайт загружается быстрее',
    tags: ['UIUX', 'design'],
  },
  {
    id: '36',
    date: '2018-09-13T15:03:23.000Z',
    title: 'Никто не знает CSS: специфичность — не каскад',
    language: 'ru',
    link: 'http://css-live.ru/css/nikto-ne-znaet-css-specifichnost-ne-kaskad.html',
    text: 'В статье объясняется что такое CSS-каскад на примере свежего модуля каскада и наследования 4 уровня',
    tags: ['css'],
  },
  {
    id: '37',
    date: '2018-08-29T15:03:23.000Z',
    title: 'Node Hero — руководство по безопасности Node.js',
    language: 'ru',
    link: 'https://tproger.ru/translations/nodejs-security-guide/',
    text: 'В последнее время почти каждую неделю мы видим новости о какой-нибудь серьёзной бреши в безопасности — чего стоят только LinkedIn и MySpace. В ходе атак произошла утечка большого количества пользовательских данных и, как следствие, пострадала репутация компании. В статье дается список рекомендаций, которые помогут улучшить безопасность вашего приложения.',
    tags: ['javaScript', 'nodeJS'],
  },
  {
    id: '38',
    date: '2018-09-04T15:03:23.000Z',
    title: 'Take A New Look At CSS Shapes',
    language: 'eng',
    link: 'https://www.smashingmagazine.com/2018/09/css-shapes/',
    text: 'Статья об использовании CSS Shapes. Фича позволяет задать форму обтекания текстом с помощью картинки.',
    tags: ['css'],
  },
  {
    id: '39',
    date: '2018-09-06T15:03:23.000Z',
    title: 'Полное понимание синхронного и асинхронного JavaScript с Async/Await',
    language: 'ru',
    link: 'https://medium.com/@stasonmars/%D0%BF%D0%BE%D0%BB%D0%BD%D0%BE%D0%B5-%D0%BF%D0%BE%D0%BD%D0%B8%D0%BC%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B8-%D0%B0%D1%81%D0%B8%D0%BD%D1%85%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-javascript-%D1%81-async-await-ba5f47f4436',
    text: 'В этой статье вы узнаете о том, что такое синхронное и асинхронное программирование в JavaScript и как применяя эти знания, работать с Async/Await.',
    tags: ['javaScript'],
  },
  {
    id: '40',
    date: '2018-09-20T15:03:23.000Z',
    title: 'Idle Until Urgent',
    language: 'eng',
    link: 'https://philipwalton.com/articles/idle-until-urgent/',
    text: 'Филип Уолтон довёл характеристику быстродействия FID (First Input Delay, время от первого взаимодействия до ответа браузера) для своего сайта от 254 мс до 100 мс и меньше. Подробно о процессе обнаружения, отладке и подходе Idle Until Urgent.',
    tags: ['javaScript'],
  },
  {
    id: '41',
    date: '2018-09-26T15:03:23.000Z',
    title: 'Как писать дату и время в интерфейсах',
    language: 'ru',
    link: 'http://mikeozornin.ru/blog/all/how-to-write-datetime-in-ui/',
    text: 'Как писать дату и время в интерфейсах: форматы, сокращения, запись диапазонов, длительности и относительных дат. Михаил Озорнин делится дизайнерскими гайдлайнами, которые пригодятся всем, кто разрабатывает интерфейсы.',
    tags: ['UIUX', 'Design'],
  },
  {
    id: '42',
    date: '2018-09-26T15:03:23.000Z',
    title: 'LottieFiles',
    language: 'eng',
    link: 'https://www.lottiefiles.com/',
    text: 'Хороший сайт с примерами анимаций для различных элементов интерфейса.',
    tags: ['site', 'UIUX', 'Design'],
  },
  {
    id: '43',
    date: '2018-06-28T15:03:23.000Z',
    title: 'Level up for UX: Design lessons from video games',
    language: 'eng',
    link: 'https://evilmartians.com/chronicles/level-up-for-ux-design-lessons-from-videogames',
    text: 'В статье описываются приемы которые можно позаимствовать из игр для дизайна интерфейса сайтов.',
    tags: ['UIUX', 'Design'],
  },
  {
    id: '44',
    date: '2018-03-28T15:03:23.000Z',
    title: 'Optimizing React: Virtual DOM explained',
    language: 'eng',
    link: 'https://evilmartians.com/chronicles/optimizing-react-virtual-dom-explained',
    text: 'Отличная статья объясняющая что такое VirtualDOM и как ускорить ваш сайт используя эти знания.',
    tags: ['javaScript'],
  },
];
